openstack/rhel-8.4-x86_64/config.json
because that fails when the distro hasn't been released yet.
Instead configure the nightlyRepoVarName attribute!
Designed to work with
https://github.com/osbuild/gitlab-ci-terraform-executor/pull/2
=> Don't use subscriptions for 8.4

aws/rhel-8.4-aarch64/config.json, aws/rhel-8.4-x86_64/config.json
because we have override logic that makes it possible to test an
arbitrary compose. While installing gitlab-ci-runner may be pulling
dependencies from the latest nightly we'd like for the remaining
duration of the test job and installation of osbuild-composer the
repositories to point to the chosen distro under test and make sure
we can override the values if necessary.
See
https://github.com/osbuild/osbuild-composer/blob/main/schutzbot/prepare-rhel-internal.sh
=> Rename nightly repo: redhat.repo -> rhel8internal.repo

aws/rhel-8.5-aarch64/config.json, aws/rhel-8.5-x86_64/config.json
RHEL 8.5 nightly images expect RHUI Beta to exist. They don't exist though.
Let's remove them.
=> aws/rhel8.5: remove RHUI repos

openstack/rhel-8.5-x86_64/main.tf
image name: rhel-guest-image-8.5-683.x86_64 (image-builder)
image id: 0a96f6b9-6b53-4b1c-b618-c0aa8f2d5d3d
=> Update openstack RHEL 8.5 image id to our own uploaded image

openstack/centos-stream-8-x86_64/config.json, openstack/fedora-33-x86_64/config.json, openstack/rhel-8-x86_64/config.json, openstack/rhel-8.4-x86_64/config.json, openstack/rhel-8.5-x86_64/config.json
There are jobs waiting for Openstack runner for over 2 hours at times
and looking at the Openstack project we're using only a 1/4 of the
limits.
=> Increase Openstack runner limit

aws/rhel-9.0-beta-nightly-aarch64/config.json, aws/rhel-9.0-beta-nightly-aarch64/main.tf, aws/rhel-9.0-beta-nightly-x86_64/config.json, aws/rhel-9.0-beta-nightly-x86_64/main.tf
Note that the RHUI workaround from 8.5 isn't needed because we're using
the guest image instead of the EC2 image (it doesn't exist yet).
This also means that the user is cloud-user instead ec2-user
=> aws: add RHEL 9.0 Beta runners

aws/_base/main.tf
20 GB is apparently not enough for RHEL 9.0 beta base tests, let's
bump it to 40 GB.
Fixes osbuild/osbuild-composer#1718
=> aws: use bigger disks

openstack/rhel-9.0-beta-nightly-x86_64/main.tf
There seems to be the same problem like we had with aws rhel-9
guest images, so updating in openstack as well.
Here's a failing run: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1557167393
Passing run with the new image: https://gitlab.com/osbuild/ci/osbuild-composer/-/jobs/1557493407
=> openstack: update rhel-9 guest images

aws/fedora-33-aarch64/config.json, aws/fedora-33-x86_64/config.json
Needed to recognize `static_context` in metadata. Mitigates
https://pagure.io/fedora-infrastructure/issue/10220.
=> aws/fedora-33: Update libmodulemd in prepare

aws/rhel-8.6-nightly-aarch64/main.tf, aws/rhel-8.6-nightly-x86_64/main.tf
Previous AMIs were not working.  I tested these new ones in the devel account before sharing.
=> aws: update RHEL 8.6 runners

aws/rhel-8.6-nightly-aarch64/config.json, aws/rhel-8.6-nightly-x86_64/config.json
Remove the 'rm redhat-rhui*' part fo the prepareScript. Our AMIs don't
contain RHUI.
=> aws: fix RHEL 8.6 configs

aws/rhel-9.0-beta-nightly-aarch64/config.json, aws/rhel-9.0-beta-nightly-x86_64/config.json, openstack/rhel-9.0-beta-nightly-x86_64/config.json
=> */rhel-9.0-beta*: use an older compose to work around an rpm size issue

aws/rhel-9.0-nightly-aarch64/config.json, aws/rhel-9.0-nightly-aarch64/main.tf, aws/rhel-9.0-nightly-x86_64/config.json, aws/rhel-9.0-nightly-x86_64/main.tf, openstack/rhel-9.0-nightly-x86_64-large/config.json, openstack/rhel-9.0-nightly-x86_64-large/main.tf, openstack/rhel-9.0-nightly-x86_64/config.json, openstack/rhel-9.0-nightly-x86_64/main.tf
Added runners for RHEL 9.0 (non-beta)
- AWS x86_64
- AWS aarch64
- Openstack x86_64
- Openstack x86_64 Large
Signed-off-by: Achilleas Koutsou <achilleas@koutsou.net>
=> Add RHEL 9.0 runners

aws/centos-stream-8-x86_64/main.tf, aws/fedora-33-x86_64/main.tf, aws/fedora-34-x86_64/main.tf, aws/rhel-8-x86_64/main.tf, aws/rhel-8.4-ga-x86_64/main.tf, aws/rhel-8.5-ga-x86_64/main.tf, aws/rhel-8.5-nightly-x86_64/main.tf, aws/rhel-8.6-nightly-x86_64/main.tf, aws/rhel-9.0-beta-nightly-x86_64/main.tf, aws/rhel-9.0-nightly-x86_64/main.tf
By my measurements, c6i.large is faster by 10% for the same price.
=> aws: replace c5.large with c6i.large

aws/centos-stream-9-aarch64/config.json, aws/centos-stream-9-x86_64/config.json, openstack/centos-stream-9-x86_64-large/config.json, openstack/centos-stream-9-x86_64/config.json
For openstack, the images were created with the default "cloud-user".
For AWS, the images were created with "ec2-user".
=> aws,openstack/centos-9: fix user names

aws/centos-stream-9-aarch64/config.json, aws/centos-stream-9-aarch64/main.tf, aws/centos-stream-9-x86_64/config.json, aws/centos-stream-9-x86_64/main.tf, openstack/centos-stream-9-x86_64-large/config.json, openstack/centos-stream-9-x86_64-large/main.tf, openstack/centos-stream-9-x86_64/config.json, openstack/centos-stream-9-x86_64/main.tf
Cherry picked commits from `main` to get the CS9 runners into the `rhos-01` branch.
Updated the `flavor-id`s for the openstack CS9 runners accordingly.
=> Add CS9 runners to RHOS-01

openstack/centos-stream-9-x86_64-large/main.tf, openstack/centos-stream-9-x86_64/main.tf
Previous one did not have growpart installed, making the root partition too small to do anything.
=> [rhos-01] Update CS9 image

openstack/rhel-8.6-nightly-x86_64-large/main.tf
IT is not necessary to use xl runner, all other large runners are
using ci-ssd.standard.large so changing it for consistency.
=> openstack: change 8.6 runner from xl to large

aws/fedora-35-x86_64/main.tf
=> [rhos01] aws/fedora35-x86: switch to c5a.large to fix booting

aws/fedora-35-x86_64/main.tf
=> aws/fedora35-x86: switch to c5a.large to fix booting

aws/_base/main.tf
We cannont provision AWS runners with newer version due to some
permission issues with VPC. This seems to be latest working version so
hard-coding it now to unblock CI.
=> aws: set max provider version to 3.72.0

rhos-01/centos-stream-8-x86_64-large/config.json, rhos-01/centos-stream-8-x86_64-large/main.tf
RHEL 8.6 has a `large` runner to run ostree tests, so CS8 runner needs the same `large` runner as well.
=> Add centos-stream-8-x86_64-large runner

rhos-01/fedora-35-x86_64-large/config.json, rhos-01/fedora-35-x86_64-large/main.tf
To run ostree-ng.sh, a "large" runner is required. https://github.com/osbuild/osbuild-composer/pull/2461 needs this PR.
=> Add fedora-35-x86_64-large as ostree-ng.sh runner

aws/fedora-36-aarch64/config.json, aws/fedora-36-aarch64/main.tf, aws/fedora-36-x86_64/config.json, aws/fedora-36-x86_64/main.tf
I've tested the fedora-36 image on c6i.large and it booted just fine, was able to login and run dnf so I consider it working. Otherwise compared to fedora-35 I've just changed the amis
=> aws: add fedora-36 runners

aws/rhel-8.6-ga-aarch64/config.json, aws/rhel-8.6-ga-x86_64/config.json, aws/rhel-9.0-ga-aarch64/config.json, aws/rhel-9.0-ga-x86_64/config.json
Reverts osbuild/gitlab-ci-terraform#67
b/c obviously runners don't work otherwise.
=> Revert "Remove RHUI repos for 8.6 and 9.0 GA"

aws/centos-stream-8-aarch64/main.tf, aws/centos-stream-9-aarch64/main.tf, aws/fedora-35-aarch64/main.tf, aws/fedora-36-aarch64/main.tf, aws/rhel-8.4-ga-aarch64/main.tf, aws/rhel-8.5-ga-aarch64/main.tf, aws/rhel-8.6-ga-aarch64/main.tf, aws/rhel-8.7-nightly-aarch64/main.tf, aws/rhel-9.0-ga-aarch64/main.tf, aws/rhel-9.1-nightly-aarch64/main.tf, rhos-01/centos-stream-8-x86_64-large/main.tf, rhos-01/centos-stream-8-x86_64/main.tf, rhos-01/centos-stream-9-x86_64-large/main.tf, rhos-01/centos-stream-9-x86_64/main.tf, rhos-01/fedora-35-x86_64-large/main.tf, rhos-01/fedora-35-x86_64/main.tf, rhos-01/fedora-36-x86_64-large/main.tf, rhos-01/fedora-36-x86_64/main.tf, rhos-01/rhel-8.4-ga-x86_64/main.tf, rhos-01/rhel-8.5-ga-x86_64-large/main.tf, rhos-01/rhel-8.5-ga-x86_64/main.tf, rhos-01/rhel-8.5-x86_64-large/main.tf, rhos-01/rhel-8.6-ga-x86_64-large/main.tf, rhos-01/rhel-8.6-ga-x86_64/main.tf, rhos-01/rhel-8.7-nightly-x86_64-large/main.tf, rhos-01/rhel-8.7-nightly-x86_64/main.tf, rhos-01/rhel-9.0-ga-x86_64-large/main.tf, rhos-01/rhel-9.0-ga-x86_64/main.tf, rhos-01/rhel-9.1-nightly-x86_64-large/main.tf, rhos-01/rhel-9.1-nightly-x86_64/main.tf
We've been using non ssd instances for over a month on RHOS-01 Openstack so I think it's fine to merge it to main.
Lately there were occasions where there were no aarch runners available so let's add an option to also use c6g.large instance.
=> Switch to non ssd isntances on RHOS-01 and add c6g.large to aarch64 spot request

aws/fedora-35-x86_64/main.tf
Fedora-35 became almost impossible to provision in the CI, adding more
instance types to fix that.
=> More instance type options for Fedora-35

aws/fedora-37-aarch64/config.json, aws/fedora-37-x86_64/config.json
The updates-testing repository is enabled in the ami by default and since we don't snapshot that repository we don't overwrite it with our snapshot and this is causing issues in CI.
=> aws/fedora-37: remove all repos during provisioning

rhos-01/fedora-37-x86_64-large/config.json, rhos-01/fedora-37-x86_64/config.json
The updates-testing repository is apparently enabled in all of the fedora-37 images by default and since we don't snapshot that repository we don't overwrite it with our snapshot and this is causing issues in CI.
=> openstack/fedora-37: remove all repos during provisioning

aws/centos-stream-8-x86_64/main.tf, aws/centos-stream-9-x86_64/main.tf, aws/fedora-36-x86_64/main.tf, aws/fedora-37-x86_64/main.tf, aws/rhel-8.4-ga-x86_64/main.tf, aws/rhel-8.5-ga-x86_64/main.tf, aws/rhel-8.6-ga-x86_64/main.tf, aws/rhel-8.7-nightly-x86_64/main.tf, aws/rhel-8.8-nightly-x86_64/main.tf, aws/rhel-9.0-ga-x86_64/main.tf, aws/rhel-9.1-nightly-x86_64/main.tf, aws/rhel-9.2-nightly-x86_64/main.tf
c6 instances are not as available as before, add c5 to fill the gaps.
=> aws: add c5 isntances for more spot options

rhos-01/fedora-37-x86_64-large/main.tf, rhos-01/fedora-37-x86_64/main.tf
Fedora-37 was using "ci-ssd" machines but these do not support nested kvm which is necessary for our CI. Changing to "ci" enables the use of nested kvm.
=> rhos-01: change fedora-37 flavor to "ci"

aws/_base/main.tf, aws/_base/variables.tf, aws/centos-stream-8-aarch64/main.tf, aws/centos-stream-8-x86_64/main.tf, aws/centos-stream-9-aarch64/main.tf, aws/centos-stream-9-x86_64/main.tf, aws/fedora-35-aarch64/main.tf, aws/fedora-35-x86_64/main.tf, aws/fedora-36-aarch64/main.tf, aws/fedora-36-x86_64/main.tf, aws/fedora-37-aarch64/main.tf, aws/fedora-37-x86_64/main.tf, aws/rhel-8.4-ga-aarch64/main.tf, aws/rhel-8.4-ga-x86_64/main.tf, aws/rhel-8.5-ga-aarch64/main.tf, aws/rhel-8.5-ga-x86_64/main.tf, aws/rhel-8.6-ga-aarch64/main.tf, aws/rhel-8.6-ga-x86_64/main.tf, aws/rhel-8.7-nightly-aarch64/main.tf, aws/rhel-8.7-nightly-x86_64/main.tf, aws/rhel-8.8-nightly-aarch64/main.tf, aws/rhel-8.8-nightly-x86_64/main.tf, aws/rhel-9.0-ga-aarch64/main.tf, aws/rhel-9.0-ga-x86_64/main.tf, aws/rhel-9.1-nightly-aarch64/main.tf, aws/rhel-9.1-nightly-x86_64/main.tf, aws/rhel-9.2-nightly-aarch64/main.tf, aws/rhel-9.2-nightly-x86_64/main.tf
In order to be able to perform fine grained analytics on our AWS budget (e.g monitor closely our CI usage). This commit brings up new tags to categorize what are each instance used for. For backward compatibility, these variables hold a default value of "unset" which means that integrating this commit will not break the CI or other tool relying on these terraforming scripts.
=> aws/tags: add a new set of tags to AWS instances

aws/centos-stream-8-aarch64/main.tf, aws/centos-stream-8-x86_64/main.tf, aws/centos-stream-9-aarch64/main.tf, aws/centos-stream-9-x86_64/main.tf, aws/fedora-35-aarch64/main.tf, aws/fedora-35-x86_64/main.tf, aws/fedora-36-aarch64/main.tf, aws/fedora-36-x86_64/main.tf, aws/fedora-37-aarch64/main.tf, aws/fedora-37-x86_64/main.tf, aws/rhel-8.4-ga-aarch64/main.tf, aws/rhel-8.4-ga-x86_64/main.tf, aws/rhel-8.5-ga-aarch64/main.tf, aws/rhel-8.5-ga-x86_64/main.tf, aws/rhel-8.6-ga-aarch64/main.tf, aws/rhel-8.6-ga-x86_64/main.tf, aws/rhel-8.7-nightly-aarch64/main.tf, aws/rhel-8.7-nightly-x86_64/main.tf, aws/rhel-8.8-nightly-aarch64/main.tf, aws/rhel-8.8-nightly-x86_64/main.tf, aws/rhel-9.0-ga-aarch64/main.tf, aws/rhel-9.0-ga-x86_64/main.tf, aws/rhel-9.1-nightly-aarch64/main.tf, aws/rhel-9.1-nightly-x86_64/main.tf, aws/rhel-9.2-nightly-aarch64/main.tf, aws/rhel-9.2-nightly-x86_64/main.tf
According to https://aws.amazon.com/ec2/spot/instance-advisor/, we used instance types that are currently prone to being killed quickly. Let's take data from the analyzer and use only instances that have the lowest probability.
=> Rebalance spot instance types

aws/rhel-8.6-ga-aarch64/main.tf, aws/rhel-8.6-ga-x86_64/main.tf, aws/rhel-8.7-ga-aarch64/config.json, aws/rhel-8.7-ga-aarch64/main.tf, aws/rhel-8.7-ga-x86_64/config.json, aws/rhel-8.7-ga-x86_64/main.tf, aws/rhel-9.0-ga-aarch64/main.tf, aws/rhel-9.0-ga-x86_64/main.tf, aws/rhel-9.1-ga-aarch64/config.json, aws/rhel-9.1-ga-aarch64/main.tf, aws/rhel-9.1-ga-x86_64/config.json, aws/rhel-9.1-ga-x86_64/main.tf
2 commits:
We used PAYG before, so I actually believe we paid for RHEL. Switch to the
Cloud Access images that are free for us.
See the relevant documentation change:
https://gitlab.cee.redhat.com/osbuild/internal-guides/-/merge_requests/148
=> Use RHEL CloudAccess images and add 8.7 and 9.1

aws/fedora-37-aarch64/config.json, aws/fedora-37-aarch64/main.tf, aws/fedora-37-x86_64/config.json, aws/fedora-37-x86_64/main.tf, rhos-01/fedora-37-x86_64-large/config.json, rhos-01/fedora-37-x86_64-large/main.tf, rhos-01/fedora-37-x86_64/config.json, rhos-01/fedora-37-x86_64/main.tf
Which also means that we don't need the prepareScript hack anymore! \o/
The hack was there due to the fact that our CI code cannot override testing repositories that are enabled in pre-GA images by default.
=> update Fedora 37 images to the GA ones

aws/_base/main.tf
We have a lot of leftovers after CI has run. We need to find a way to automatically remove outdated EC2 fleet instances. Valid_until is a variable that if set will timeout the request. With the combination of "terminate_instances_with_expiration" it should correctly kill the instance when the 4h mark is reached.
=> base: 4h timeout on the spot fleet request

gcp/rhel-8.8-nightly-x86_64/config.json, gcp/rhel-9.2-nightly-x86_64/config.json
Without this provisioning of the runners on nightly pipelines fail.
@atodorov This should fix the issue with provisioning of these runners on the nightly scheduled pipelines.
=> GCP: Add nightly repos to prepareScript

aws/centos-stream-9-aarch64/main.tf, aws/centos-stream-9-x86_64/main.tf
For some reason the images we used before are gone so I created new ones using image builder service.
=> aws: reupload deleted centos-stream-9 images

aws/rhel-8.9-nightly-aarch64/main.tf
previously imported AMI was aarch64 but incorrectly tagged as x86_64 leading to failures when launching VMs from it.
=> COMPOSER-1959: Update 8.9 aarch64 AMI to RHEL-8.9.0-20230503.20

rhos-01/centos-stream-8-x86_64-large/main.tf, rhos-01/centos-stream-8-x86_64/main.tf
This build has a newer kernel which includes support for `LOOP_CONFIGURE`.
https://bugzilla.redhat.com/show_bug.cgi?id=1881760
https://github.com/osbuild/osbuild/commit/da11ef4eb014c22f425a2ecfebc2d260f8d95ee9
=> rhos-01/centos-stream-8-x86_64: update to more recent compose

rhos-01/centos-stream-8-x86_64-large/main.tf, rhos-01/centos-stream-8-x86_64/main.tf
The previous image didn't have the correct architecture set.
---
https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/877555943 this one worked :)
=> rhos-01/centos-stream-8-x86_64: include correct architecture

aws/centos-stream-8-aarch64/config.json, aws/centos-stream-8-aarch64/main.tf, aws/centos-stream-8-x86_64/config.json, aws/centos-stream-8-x86_64/main.tf
Images were over 2 years old and were causing issues during updates in CI. Images were created by Image builder service.
=> aws: Update centos-stream-8 images

aws/_base/main.tf
b/c the timeout in GitLab is 5hrs and b/c the Image Tests job on x86_64 RHEL 8.9 takes more than 4hrs.
=> Bump spot instance time to 5hrs

aws/_base/main.tf
There is no credentials file specified, and terraform errors out on newer plugin versions.
=> aws: remove profile from aws provider

aws/fedora-39-aarch64/main.tf, aws/fedora-39-x86_64/main.tf
Fixes an issue with s3cmd in Fedora 39, x86_64. For successfull job execution see https://gitlab.com/redhat/services/products/image-builder/ci/osbuild-composer/-/pipelines/1095699455 (from https://github.com/osbuild/osbuild-composer/pull/3820)
=> Update Fedora 39 AMIs

aws/fedora-38-aarch64/main.tf
The current one is apparently broken in aws.
=> aws: switch to older fedora-38-aarch64 ami

aws/_base/main.tf, aws/_base/variables.tf
The idea is to test the secure instance thing as it would be used in the service. This way we can spin up a runner which is allowed to spin up a secure instance for itself.
Required by https://github.com/osbuild/gitlab-ci-terraform-executor/pull/31
=> aws: allow setting an instance profile on the runner

aws/rhel-8.10-ga-aarch64/main.tf, aws/rhel-8.10-ga-x86_64/main.tf, aws/rhel-9.4-ga-aarch64/main.tf, aws/rhel-9.4-ga-x86_64/main.tf, gcp/rhel-8.10-ga-x86_64/main.tf, gcp/rhel-9.4-ga-x86_64/main.tf, rhos-01/rhel-8.10-ga-x86_64-large/config.json, rhos-01/rhel-8.10-ga-x86_64-large/main.tf, rhos-01/rhel-8.10-ga-x86_64/config.json, rhos-01/rhel-8.10-ga-x86_64/main.tf
The refresh bot failed because the rhel 8.10 placeholders on openstack weren't there.
=> add rhel 8.10 and 9.4 ga images

.github/workflows/terraform.yml
Should we update to `ubuntu-latest` and not care or switch to `ubuntu-22.04` before end of standard support (April 2025)
note: `ubuntu-24.04` github-runner is still beta as of today
=> github/workflows/terraform: update to latest worker

aws/fedora-39-aarch64/main.tf, aws/fedora-39-x86_64/main.tf, aws/fedora-40-aarch64/main.tf, aws/fedora-40-x86_64/main.tf, aws/fedora-41-aarch64/main.tf, aws/fedora-41-x86_64/main.tf
Update Fedora AMIs to the latest ones that were rebuilt by the ci-image-refresh-bot.
=> Update Fedora AMIs to `ci-fedora-*-refresh-01-12-2024`
