openstack/centos-stream-8-x86_64/config.json, openstack/centos-stream-8-x86_64/main.tf, openstack/fedora-32-x86_64/config.json, openstack/fedora-33-x86_64/config.json, openstack/rhel-8-x86_64/config.json
add centos stream to openstack and bump up quotas
=> Centos on openstack

aws/rhel-8.5-aarch64/config.json, aws/rhel-8.5-aarch64/main.tf, aws/rhel-8.5-x86_64/config.json, aws/rhel-8.5-x86_64/main.tf, openstack/rhel-8.5-x86_64/config.json, openstack/rhel-8.5-x86_64/main.tf
Use " RHEL-8.5.0-x86_64-nightly-latest" image
=> openstack: Add RHEL 8.5 runner

aws/rhel-8.5-aarch64/main.tf, aws/rhel-8.5-x86_64/main.tf
```
[fedora@toolbox kite-image]$ aws --profile "saml" ec2 describe-images --region us-east-1 --filter Name=name,Values=rhel-ec2-8.5-693.x86_64
{
"Images": [
{
"Architecture": "x86_64",
"CreationDate": "2021-06-29T06:54:56.000Z",
"ImageId": "ami-0c14d21e741b97c48",
"ImageLocation": "933752197999/rhel-ec2-8.5-693.x86_64",
"ImageType": "machine",
"Public": false,
"OwnerId": "933752197999",
"PlatformDetails": "Linux/UNIX",
"UsageOperation": "RunInstances",
"State": "available",
"BlockDeviceMappings": [
{
"DeviceName": "/dev/sda1",
"Ebs": {
"DeleteOnTermination": true,
"SnapshotId": "snap-066c28bcfee182912",
"VolumeSize": 10,
"VolumeType": "gp2",
"Encrypted": false
}
}
],
"EnaSupport": true,
"Hypervisor": "xen",
"Name": "rhel-ec2-8.5-693.x86_64",
"RootDeviceName": "/dev/sda1", …
```
=> Update AWS RHEL 8.5 ami for x86_64 and aarch64

openstack/_base/main.tf, openstack/_base/variables.tf, openstack/centos-stream-8-x86_64/main.tf, openstack/fedora-33-x86_64/main.tf, openstack/rhel-8-x86_64/main.tf, openstack/rhel-8.4-x86_64/main.tf, openstack/rhel-8.5-x86_64-large/config.json, openstack/rhel-8.5-x86_64-large/main.tf, openstack/rhel-9.0-beta-nightly-x86_64/main.tf
We need a more powerful runner for some ostree tests. This also enables
to define a different flavor for each runner.
=> openstack: add large RHEL-8.5 runner

openstack/rhel-8.4-ga-x86_64/main.tf
blocks https://github.com/osbuild/image-builder/pull/252
=> Add required flavor_id

aws/rhel-8.6-nightly-aarch64/config.json, aws/rhel-8.6-nightly-aarch64/main.tf, aws/rhel-8.6-nightly-x86_64/config.json, aws/rhel-8.6-nightly-x86_64/main.tf, openstack/rhel-8.6-nightly-x86_64-large/config.json, openstack/rhel-8.6-nightly-x86_64-large/main.tf, openstack/rhel-8.6-nightly-x86_64/config.json, openstack/rhel-8.6-nightly-x86_64/main.tf
Copied and adapted RHEL 8.5 runners.  Added "large" flavour for openstack as well.
I'm not sure I set up everything correctly so please verify the image IDs, especially for the AWS images.
=> Add runners for RHEL 8.6

aws/rhel-8-aarch64/config.json, aws/rhel-8-aarch64/main.tf, aws/rhel-8-x86_64/config.json, aws/rhel-8-x86_64/main.tf, openstack/rhel-8-x86_64/config.json, openstack/rhel-8-x86_64/main.tf
We need them to unblock https://github.com/osbuild/osbuild/pull/835
This partially reverts commit d36255fe83688d2299a7b717291bda20d0b8d634.
=> bring back rhel-8 runners temporarily

aws/rhel-9.0-nightly-aarch64/config.json, aws/rhel-9.0-nightly-x86_64/config.json
Images were built by composer which uses ec2-user instead of cloud-user.
=> aws/rhel-9.0: fix the username

openstack/centos-stream-9-x86_64-large/main.tf, openstack/centos-stream-9-x86_64/main.tf
Something went wrong with the upload of the previous image.
Reuploaded now (and boot tested).
=> openstack/cs9: update image

rhos-01/centos-stream-8-x86_64/config.json, rhos-01/centos-stream-9-x86_64-large/config.json, rhos-01/centos-stream-9-x86_64/config.json, rhos-01/rhel-8.4-ga-x86_64/config.json, rhos-01/rhel-8.5-ga-x86_64-large/config.json, rhos-01/rhel-8.5-ga-x86_64/config.json, rhos-01/rhel-8.5-x86_64-large/config.json, rhos-01/rhel-8.6-nightly-x86_64-large/config.json, rhos-01/rhel-8.6-nightly-x86_64/config.json, rhos-01/rhel-9.0-nightly-x86_64-large/config.json, rhos-01/rhel-9.0-nightly-x86_64/config.json
See commit bf3c8236575eae32db6262b38e889fed7ca0c933
=> remove maxInstances for rhos-01 Openstack

rhos-01/centos-stream-8-x86_64/config.json, rhos-01/centos-stream-9-x86_64-large/config.json, rhos-01/centos-stream-9-x86_64/config.json
Signed-off-by: Tomas Hozza <thozza@redhat.com>
=> Fix syntax after 61edeab9c960ba87c2e93601658eb9054dc327cf

aws/_base/data.tf
I was wondering if this is possible in pure terraform and sure it is.
Tested locally.
=> aws: spread load across both internal subnets

aws/rhel-8.6-ga-aarch64/config.json, aws/rhel-8.6-ga-x86_64/config.json, aws/rhel-9.0-ga-aarch64/config.json, aws/rhel-9.0-ga-x86_64/config.json
these repos are causing the Composer Test failures in https://github.com/osbuild/osbuild/pull/1051
=> Remove RHUI repos for 8.6 and 9.0 GA

aws/fedora-37-aarch64/config.json, aws/fedora-37-aarch64/main.tf, aws/fedora-37-x86_64/config.json, aws/fedora-37-x86_64/main.tf, rhos-01/fedora-37-x86_64-large/config.json, rhos-01/fedora-37-x86_64-large/main.tf, rhos-01/fedora-37-x86_64/config.json, rhos-01/fedora-37-x86_64/main.tf
Powered by images from the 20220815 compose.
=> Add fedora-37 runners

aws/centos-stream-9-aarch64/config.json, aws/centos-stream-9-x86_64/config.json, aws/rhel-9.1-nightly-x86_64/main.tf
=> Fixes for the new AMIs

gcp/_base/main.tf, gcp/_base/outputs.tf, gcp/_base/variables.tf, gcp/centos-stream-8-x86_64/config.json, gcp/centos-stream-8-x86_64/main.tf, gcp/centos-stream-9-x86_64/config.json, gcp/centos-stream-9-x86_64/main.tf, gcp/fedora-37-x86_64/config.json, gcp/fedora-37-x86_64/main.tf, gcp/rhel-8.7-ga-x86_64/config.json, gcp/rhel-8.7-ga-x86_64/main.tf, gcp/rhel-8.8-nightly-x86_64/config.json, gcp/rhel-8.8-nightly-x86_64/main.tf, gcp/rhel-9.1-ga-x86_64/config.json, gcp/rhel-9.1-ga-x86_64/main.tf, gcp/rhel-9.2-nightly-x86_64/config.json, gcp/rhel-9.2-nightly-x86_64/main.tf
We have access to internal network in GCP now so we can expand our CI with new runners in GCP.
=> Add GCP provider

aws/fedora-38-aarch64/config.json, aws/fedora-38-aarch64/main.tf, aws/fedora-38-x86_64/config.json, aws/fedora-38-x86_64/main.tf
Fedora-38 is not out yet so there is a comment with the COMPOSE_ID and it should be updated once GA is available.
=> aws: add fedora-38 runners

aws/rhel-9.2-ga-aarch64/config.json, aws/rhel-9.2-ga-aarch64/main.tf, aws/rhel-9.2-ga-x86_64/config.json, aws/rhel-9.2-ga-x86_64/main.tf, gcp/rhel-9.2-ga-x86_64/config.json, gcp/rhel-9.2-ga-x86_64/main.tf, rhos-01/rhel-9.2-ga-x86_64-large/config.json, rhos-01/rhel-9.2-ga-x86_64-large/main.tf, rhos-01/rhel-9.2-ga-x86_64/config.json, rhos-01/rhel-9.2-ga-x86_64/main.tf
Also removes the nightly prepare script, after the update the nightlies can be dropped.
=> rhel-9-ga: stub so the image refresh bot can update them

aws/fedora-39-aarch64/main.tf
Jakub was able to copy this AMI from the community release!
=> Updated Fedora-39 aarch64 AMI

aws/rhel-8.10-ga-aarch64/config.json, aws/rhel-8.10-ga-aarch64/main.tf, aws/rhel-8.10-ga-x86_64/config.json, aws/rhel-8.10-ga-x86_64/main.tf, aws/rhel-9.4-ga-aarch64/config.json, aws/rhel-9.4-ga-aarch64/main.tf, aws/rhel-9.4-ga-x86_64/config.json, aws/rhel-9.4-ga-x86_64/main.tf, gcp/rhel-8.10-ga-x86_64/config.json, gcp/rhel-8.10-ga-x86_64/main.tf, gcp/rhel-9.4-ga-x86_64/config.json, gcp/rhel-9.4-ga-x86_64/main.tf, rhos-01/rhel-9.4-ga-x86_64-large/config.json, rhos-01/rhel-9.4-ga-x86_64-large/main.tf, rhos-01/rhel-9.4-ga-x86_64/config.json, rhos-01/rhel-9.4-ga-x86_64/main.tf
These can be built by the ci image refresh bot.
---
The bot will open a PR like https://github.com/osbuild/gitlab-ci-terraform/pull/132
=> add RHEL 8.10 and 9.4 placeholders

rhos-01/fedora-40-x86_64-large/config.json, rhos-01/fedora-40-x86_64-large/main.tf, rhos-01/fedora-40-x86_64/config.json, rhos-01/fedora-40-x86_64/main.tf
This image is needed for the libvirt tests in composer.
=> rhos-01: add fedora-40 placeholder

aws/rhel-9.6-nightly-aarch64/config.json, aws/rhel-9.6-nightly-aarch64/main.tf, aws/rhel-9.6-nightly-x86_64/config.json, aws/rhel-9.6-nightly-x86_64/main.tf, gcp/rhel-9.6-nightly-x86_64/config.json, gcp/rhel-9.6-nightly-x86_64/main.tf, rhos-01/rhel-9.6-nightly-x86_64-large/config.json, rhos-01/rhel-9.6-nightly-x86_64-large/main.tf, rhos-01/rhel-9.6-nightly-x86_64/config.json, rhos-01/rhel-9.6-nightly-x86_64/main.tf
=> Add RHEL-9.6 placeholders
